# THIS FILE WAS AUTO-GENERATED BY CADWYN. DO NOT EVER TRY TO EDIT IT BY HAND

import typing
import pydantic
from typing import Optional
from pydantic import BaseModel
from deplio.models.data.head.db.cron import CronJobStatus, HTTPExecutor

class PostCronJobRequest(BaseModel):
    status: CronJobStatus = CronJobStatus.ACTIVE
    executor: HTTPExecutor
    schedule: str
    metadata: Optional[dict[str, str]] = None