# THIS FILE WAS AUTO-GENERATED BY CADWYN. DO NOT EVER TRY TO EDIT IT BY HAND

from datetime import date
from typing import Optional
from pydantic import BaseModel


class Versions(BaseModel):
    latest: date
    current: Optional[date]
    team: Optional[date]
