repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: pnpm run lint
        language: system
        pass_filenames: false
      - id: format
        name: Format
        entry: pnpm run format
        language: system
        pass_filenames: false
