/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Body
 */
export interface Body {
}

/**
 * Check if a given object implements the Body interface.
 */
export function instanceOfBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BodyFromJSON(json: any): Body {
    return BodyFromJSONTyped(json, false);
}

export function BodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Body {
    return json;
}

export function BodyToJSON(value?: Body | null): any {
    return value;
}

