/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Current
 */
export interface Current {
}

/**
 * Check if a given object implements the Current interface.
 */
export function instanceOfCurrent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CurrentFromJSON(json: any): Current {
    return CurrentFromJSONTyped(json, false);
}

export function CurrentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Current {
    return json;
}

export function CurrentToJSON(value?: Current | null): any {
    return value;
}

