/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Data } from './Data';
import {
    DataFromJSON,
    DataFromJSONTyped,
    DataToJSON,
} from './Data';

/**
 * 
 * @export
 * @interface DeplioWarning
 */
export interface DeplioWarning {
    /**
     * 
     * @type {string}
     * @memberof DeplioWarning
     */
    message: string;
    /**
     * 
     * @type {Data}
     * @memberof DeplioWarning
     */
    data?: Data;
}

/**
 * Check if a given object implements the DeplioWarning interface.
 */
export function instanceOfDeplioWarning(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DeplioWarningFromJSON(json: any): DeplioWarning {
    return DeplioWarningFromJSONTyped(json, false);
}

export function DeplioWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeplioWarning {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': !exists(json, 'data') ? undefined : DataFromJSON(json['data']),
    };
}

export function DeplioWarningToJSON(value?: DeplioWarning | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': DataToJSON(value.data),
    };
}

