/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Data } from './Data';
import {
    DataFromJSON,
    DataFromJSONTyped,
    DataToJSON,
} from './Data';

/**
 * 
 * @export
 * @interface DeplioError
 */
export interface DeplioError {
    /**
     * 
     * @type {string}
     * @memberof DeplioError
     */
    message: string;
    /**
     * 
     * @type {Data}
     * @memberof DeplioError
     */
    data?: Data;
    /**
     * 
     * @type {string}
     * @memberof DeplioError
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the DeplioError interface.
 */
export function instanceOfDeplioError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DeplioErrorFromJSON(json: any): DeplioError {
    return DeplioErrorFromJSONTyped(json, false);
}

export function DeplioErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeplioError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': !exists(json, 'data') ? undefined : DataFromJSON(json['data']),
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function DeplioErrorToJSON(value?: DeplioError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': DataToJSON(value.data),
        'timestamp': value.timestamp,
    };
}

