/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Body } from './Body';
import {
    BodyFromJSON,
    BodyFromJSONTyped,
    BodyToJSON,
} from './Body';
import type { DeletedAt } from './DeletedAt';
import {
    DeletedAtFromJSON,
    DeletedAtFromJSONTyped,
    DeletedAtToJSON,
} from './DeletedAt';
import type { Headers } from './Headers';
import {
    HeadersFromJSON,
    HeadersFromJSONTyped,
    HeadersToJSON,
} from './Headers';
import type { ResponseTimeNs } from './ResponseTimeNs';
import {
    ResponseTimeNsFromJSON,
    ResponseTimeNsFromJSONTyped,
    ResponseTimeNsToJSON,
} from './ResponseTimeNs';
import type { StatusCode } from './StatusCode';
import {
    StatusCodeFromJSON,
    StatusCodeFromJSONTyped,
    StatusCodeToJSON,
} from './StatusCode';

/**
 * 
 * @export
 * @interface QResponse
 */
export interface QResponse {
    /**
     * 
     * @type {string}
     * @memberof QResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof QResponse
     */
    created_at: Date;
    /**
     * 
     * @type {DeletedAt}
     * @memberof QResponse
     */
    deleted_at: DeletedAt;
    /**
     * 
     * @type {string}
     * @memberof QResponse
     */
    request_id: string;
    /**
     * 
     * @type {StatusCode}
     * @memberof QResponse
     */
    status_code: StatusCode;
    /**
     * 
     * @type {Body}
     * @memberof QResponse
     */
    body: Body;
    /**
     * 
     * @type {Headers}
     * @memberof QResponse
     */
    headers: Headers;
    /**
     * 
     * @type {ResponseTimeNs}
     * @memberof QResponse
     */
    response_time_ns: ResponseTimeNs;
}

/**
 * Check if a given object implements the QResponse interface.
 */
export function instanceOfQResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "created_at" in value;
    isInstance = isInstance && "deleted_at" in value;
    isInstance = isInstance && "request_id" in value;
    isInstance = isInstance && "status_code" in value;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "headers" in value;
    isInstance = isInstance && "response_time_ns" in value;

    return isInstance;
}

export function QResponseFromJSON(json: any): QResponse {
    return QResponseFromJSONTyped(json, false);
}

export function QResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created_at': (new Date(json['created_at'])),
        'deleted_at': DeletedAtFromJSON(json['deleted_at']),
        'request_id': json['request_id'],
        'status_code': StatusCodeFromJSON(json['status_code']),
        'body': BodyFromJSON(json['body']),
        'headers': HeadersFromJSON(json['headers']),
        'response_time_ns': ResponseTimeNsFromJSON(json['response_time_ns']),
    };
}

export function QResponseToJSON(value?: QResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': (value.created_at.toISOString()),
        'deleted_at': DeletedAtToJSON(value.deleted_at),
        'request_id': value.request_id,
        'status_code': StatusCodeToJSON(value.status_code),
        'body': BodyToJSON(value.body),
        'headers': HeadersToJSON(value.headers),
        'response_time_ns': ResponseTimeNsToJSON(value.response_time_ns),
    };
}

