/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Body } from './Body';
import {
    BodyFromJSON,
    BodyFromJSONTyped,
    BodyToJSON,
} from './Body';
import type { DeletedAt } from './DeletedAt';
import {
    DeletedAtFromJSON,
    DeletedAtFromJSONTyped,
    DeletedAtToJSON,
} from './DeletedAt';
import type { Headers } from './Headers';
import {
    HeadersFromJSON,
    HeadersFromJSONTyped,
    HeadersToJSON,
} from './Headers';
import type { ResponseTimeNs } from './ResponseTimeNs';
import {
    ResponseTimeNsFromJSON,
    ResponseTimeNsFromJSONTyped,
    ResponseTimeNsToJSON,
} from './ResponseTimeNs';
import type { StatusCode } from './StatusCode';
import {
    StatusCodeFromJSON,
    StatusCodeFromJSONTyped,
    StatusCodeToJSON,
} from './StatusCode';

/**
 * 
 * @export
 * @interface QResponse
 */
export interface QResponse {
    /**
     * 
     * @type {string}
     * @memberof QResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof QResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {DeletedAt}
     * @memberof QResponse
     */
    deletedAt: DeletedAt;
    /**
     * 
     * @type {string}
     * @memberof QResponse
     */
    requestId: string;
    /**
     * 
     * @type {StatusCode}
     * @memberof QResponse
     */
    statusCode: StatusCode;
    /**
     * 
     * @type {Body}
     * @memberof QResponse
     */
    body: Body;
    /**
     * 
     * @type {Headers}
     * @memberof QResponse
     */
    headers: Headers;
    /**
     * 
     * @type {ResponseTimeNs}
     * @memberof QResponse
     */
    responseTimeNs: ResponseTimeNs;
}

/**
 * Check if a given object implements the QResponse interface.
 */
export function instanceOfQResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "deletedAt" in value;
    isInstance = isInstance && "requestId" in value;
    isInstance = isInstance && "statusCode" in value;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "headers" in value;
    isInstance = isInstance && "responseTimeNs" in value;

    return isInstance;
}

export function QResponseFromJSON(json: any): QResponse {
    return QResponseFromJSONTyped(json, false);
}

export function QResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'deletedAt': DeletedAtFromJSON(json['deleted_at']),
        'requestId': json['request_id'],
        'statusCode': StatusCodeFromJSON(json['status_code']),
        'body': BodyFromJSON(json['body']),
        'headers': HeadersFromJSON(json['headers']),
        'responseTimeNs': ResponseTimeNsFromJSON(json['response_time_ns']),
    };
}

export function QResponseToJSON(value?: QResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'deleted_at': DeletedAtToJSON(value.deletedAt),
        'request_id': value.requestId,
        'status_code': StatusCodeToJSON(value.statusCode),
        'body': BodyToJSON(value.body),
        'headers': HeadersToJSON(value.headers),
        'response_time_ns': ResponseTimeNsToJSON(value.responseTimeNs),
    };
}

