/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseTimeNs
 */
export interface ResponseTimeNs {
}

/**
 * Check if a given object implements the ResponseTimeNs interface.
 */
export function instanceOfResponseTimeNs(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseTimeNsFromJSON(json: any): ResponseTimeNs {
    return ResponseTimeNsFromJSONTyped(json, false);
}

export function ResponseTimeNsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTimeNs {
    return json;
}

export function ResponseTimeNsToJSON(value?: ResponseTimeNs | null): any {
    return value;
}

