/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusCode
 */
export interface StatusCode {
}

/**
 * Check if a given object implements the StatusCode interface.
 */
export function instanceOfStatusCode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatusCodeFromJSON(json: any): StatusCode {
    return StatusCodeFromJSONTyped(json, false);
}

export function StatusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusCode {
    return json;
}

export function StatusCodeToJSON(value?: StatusCode | null): any {
    return value;
}

