/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Current } from './Current';
import {
    CurrentFromJSON,
    CurrentFromJSONTyped,
    CurrentToJSON,
} from './Current';
import type { Team } from './Team';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
} from './Team';

/**
 * 
 * @export
 * @interface Versions
 */
export interface Versions {
    /**
     * 
     * @type {Date}
     * @memberof Versions
     */
    latest: Date;
    /**
     * 
     * @type {Current}
     * @memberof Versions
     */
    current: Current;
    /**
     * 
     * @type {Team}
     * @memberof Versions
     */
    team: Team;
}

/**
 * Check if a given object implements the Versions interface.
 */
export function instanceOfVersions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "latest" in value;
    isInstance = isInstance && "current" in value;
    isInstance = isInstance && "team" in value;

    return isInstance;
}

export function VersionsFromJSON(json: any): Versions {
    return VersionsFromJSONTyped(json, false);
}

export function VersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Versions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latest': (new Date(json['latest'])),
        'current': CurrentFromJSON(json['current']),
        'team': TeamFromJSON(json['team']),
    };
}

export function VersionsToJSON(value?: Versions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latest': (value.latest.toISOString().substring(0,10)),
        'current': CurrentToJSON(value.current),
        'team': TeamToJSON(value.team),
    };
}

