# THIS FILE WAS AUTO-GENERATED BY CADWYN. DO NOT EVER TRY TO EDIT IT BY HAND

from typing import Optional
from uuid import UUID
from pydantic import AwareDatetime, BaseModel


class DeplioModel(BaseModel):
    id: UUID


class TimestampedDeplioModel(DeplioModel):
    created_at: AwareDatetime
    deleted_at: Optional[AwareDatetime]
