# THIS FILE WAS AUTO-GENERATED BY CADWYN. DO NOT EVER TRY TO EDIT IT BY HAND

import abc
from typing import Any, Optional
from pydantic import BaseModel


class Warning(BaseModel):
    message: str
    data: Optional[dict[str, Any]] = None


class DeplioResponse(BaseModel, abc.ABC):
    __abstract__ = True
    warnings: list[Warning]
