/* tslint:disable */
/* eslint-disable */
/**
 * Deplio
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-02-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetLatestAPIVersionVersionGetRequest {
    deplioVersion?: Date;
}

/**
 * 
 */
export class MiscApi extends runtime.BaseAPI {

    /**
     * Retrieve the latest version of the API
     * Get Latest Api Version
     */
    async getLatestAPIVersionVersionGetRaw(requestParameters: GetLatestAPIVersionVersionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.deplioVersion !== undefined && requestParameters.deplioVersion !== null) {
            headerParameters['deplio-version'] = String(requestParameters.deplioVersion);
        }

        const response = await this.request({
            path: `/version`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Retrieve the latest version of the API
     * Get Latest Api Version
     */
    async getLatestAPIVersionVersionGet(requestParameters: GetLatestAPIVersionVersionGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getLatestAPIVersionVersionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
