services:
  redis:
    image: redis:alpine
    container_name: deplio-redis
    ports:
      - "6379:6379"
  kv-server:
    image: darthbenro008/upstash-redis-local:latest
    command: "--addr :6380 --redis redis:6379 --token deplio"
    container_name: deplio-kv-server
    depends_on:
      - redis
    ports:
      - "6380:6380"
